version: '3.4'

services:
  ui:
    stdin_open: true
    restart: always
    build:
      context: web
      dockerfile: Dockerfile
    volumes:
      - "app/node_modules"
    depends_on: 
        - web-api
    ports:
      - 5000:3000
  
  web-api:
    build:
      context: WebAPI
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db
    ports:
      - 7000:80
  
  db:
    image: postgres:10.11
    restart: always
    environment:
      POSTGRES_DB: "diplomadatabase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - "./WebAPI/initdb:/docker-entrypoint-initdb.d"