version: '3.4'

services:
  ui:
    stdin_open: true
    restart: always
    build:
      context: web
      dockerfile: Dockerfile
    environment: 
      - REACT_APP_BACK_URL=http://web-api:80/
    depends_on: 
        - web-api
    ports:
      - 5000:3000
  
  web-api:
    build:
      context: WebAPI
      dockerfile: Dockerfile
    restart: always
    environment: 
      - ASPNETCORE_ENVIRONMENT=docker
    depends_on:
      - db
    ports:
      - 7000:80
  
  db:
    image: postgres:10.11
    restart: always
    environment:
      POSTGRES_DB: "diplomadatabase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - "./WebAPI/initdb:/docker-entrypoint-initdb.d"