version: '3.4'

services:
  web-api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 7000:80
  
  db:
    image: postgres:10.11
    restart: always
    environment:
      POSTGRES_DB: "diplomadatabase"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d