version: '3.4'

services:
  diploma-ui:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "/app/node_modules"
      - "./:/app"
    ports:
      - 3007:3000